Basic questions before working on a dataset

In [4]:
import seaborn as sns
import pandas as pd

df = sns.load_dataset("titanic")

How big is the Data Set?

In [5]:
df.shape  #tells the number of rows and columns. or How big is the dataset.

(891, 15)

How does the data look like?

In [6]:
df.head() #return's top 5 rows from the "df" dataset.

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

df.head() gives the preview of dataset and helps in deciding which columns to to work on or which one to remove.

In [7]:
df.sample(5) #return's 5 random rows from the "df" dataset

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
386,0,3,male,1.0,5,2,46.9000,S,Third,child,False,NaN,Southampton,no,False
786,1,3,female,18.0,0,0,7.4958,S,Third,woman,False,NaN,Southampton,yes,True
122,0,2,male,32.5,1,0,30.0708,C,Second,man,True,NaN,Cherbourg,no,False
409,0,3,female,NaN,3,1,25.4667,S,Third,woman,False,NaN,Southampton,no,False
849,1,1,female,NaN,1,0,89.1042,C,First,woman,False,C,Cherbourg,yes,False

Whats is the datatype of columns?

In [13]:
df.info()

<class 'pandas.DataFrame'>
Index: 714 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     714 non-null    int64
 1   pclass       714 non-null    int64
 2   sex          714 non-null    str
 3   age          714 non-null    int64
 4   sibsp        714 non-null    int64
 5   parch        714 non-null    int64
 6   fare         714 non-null    float64
 7   embarked     712 non-null    str
 8   class        714 non-null    category
 9   who          714 non-null    str
 10  adult_male   714 non-null    bool
 11  deck         184 non-null    category
 12  embark_town  712 non-null    str
 13  alive        714 non-null    str
 14  alone        714 non-null    bool
dtypes: bool(2), category(2), float64(1), int64(5), str(5)
memory usage: 86.4 KB

In [12]:
df = df.dropna(subset=["age"])
df["age"] = df["age"].astype(int)
df.info()

<class 'pandas.DataFrame'>
Index: 714 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     714 non-null    int64
 1   pclass       714 non-null    int64
 2   sex          714 non-null    str
 3   age          714 non-null    int64
 4   sibsp        714 non-null    int64
 5   parch        714 non-null    int64
 6   fare         714 non-null    float64
 7   embarked     712 non-null    str
 8   class        714 non-null    category
 9   who          714 non-null    str
 10  adult_male   714 non-null    bool
 11  deck         184 non-null    category
 12  embark_town  712 non-null    str
 13  alive        714 non-null    str
 14  alone        714 non-null    bool
dtypes: bool(2), category(2), float64(1), int64(5), str(5)
memory usage: 86.4 KB

Are there any missing values?

In [14]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           530
embark_town      2
alive            0
alone            0
dtype: int64

how does the data look mathematically?

In [15]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  714.000000  714.000000  714.000000  714.000000  714.000000  714.000000
mean     0.406162    2.236695   29.679272    0.512605    0.431373   34.694514
std      0.491460    0.838250   14.536483    0.929783    0.853289   52.918930
min      0.000000    1.000000    0.000000    0.000000    0.000000    0.000000
25%      0.000000    1.000000   20.000000    0.000000    0.000000    8.050000
50%      0.000000    2.000000   28.000000    0.000000    0.000000   15.741700
75%      1.000000    3.000000   38.000000    1.000000    1.000000   33.375000
max      1.000000    3.000000   80.000000    5.000000    6.000000  512.329200

Are there any duplicate values?

In [17]:
df.duplicated().sum()

np.int64(38)

How is the correlation between columns?

In [19]:
df.corr()

ValueError: could not convert string to float: 'male'